print("dsc.gg/getmoonexec")
print("dsc.gg/getmooncracks")
print("on top")

--skids kys
--SKIDS HERES A MESSAGES FOR YOU!! your nothing in life, fucking discord mods, honey bun eater nigger, fuck yourself, furry, femboy, you goon to femboy porn, roblox rule34 loser
--, i hope your entire life dies, i hope you fall into a deep state of depression, honestly no one loves you, i will find you and kill you, i will shoot you with a loaded shotgun nigger
--, i will kill your siblings, pets, and parents, i will fucking beat the living shit out of you, js fuck you
--SKIDS IF YOU SADLY HAVENT STABBED A KNIFE IN YOUR CHEST YET, READ THIS, alright fucking whore bastard your still here.. please just take a sharp knife and stab your chest, ITS NOT HARD NIGGER RETARD WHORE
--SKIDS, FEMBOYS, LGBTQ+ RETARDS, FURRYS, ETC GO FUCKING STAB A KNIFE IN YOUR CHEST STUPID BASTARD I HOPE YOU DIE RETARDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD FUCK YOUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU
